[package]
name = "rust_server_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0"
rusqlite = "0.26.0"
log = "0.4.14"